# syntax = docker/dockerfile:experimental
## log4cplus
FROM arm64v8/alpine:edge AS log4cplus

# Environment
ENV LOG4CPLUS="1.2.2"
ARG BUILD_PKGS="build-base gawk clang lld "
ARG CFLAGS="-O2 -pthread -pipe -fPIC -FORTIFY_SOURCE=2 -fPIE -fuse-ld=lld "
ARG CXXFLAGS="${CFLAGS} "
ARG LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -fuse-ld=lld "
ENV CC="clang "
ENV CXX="clang++ "

# build library
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update ${BUILD_PKGS}
RUN mkdir -p /usr/local/src \
    && wget "https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/${LOG4CPLUS}/log4cplus-${LOG4CPLUS}.tar.bz2/" -O log4cplus.tar.bz2 \
    && tar xf log4cplus.tar.bz2 --strip-components=1 -C /usr/local/src \
    && rm log4cplus.tar.bz2
RUN cd /usr/local/src \
    && ./configure  \
        CFLAGS="${CFLAGS}" CXXFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}" \
    && make -j$(nproc) \
    && make install DESTDIR=/tmp/root
RUN ldconfig /


## botan
FROM arm64v8/alpine:edge AS botan

# Environment
ENV BOTAN="2.10.0"
ARG BUILD_PKGS="build-base gawk python boost-dev bzip2-dev libressl-dev zlib-dev sqlite-dev "

# build library
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update ${BUILD_PKGS}
RUN mkdir -p /usr/local/src \
    && wget "https://botan.randombit.net/releases/Botan-${BOTAN}.tgz" -O botan.tar.gz \
    && tar xf botan.tar.gz --strip-components=1 -C /usr/local/src \
    && rm botan.tar.gz
RUN cd /usr/local/src \
    && ./configure.py \
        --disable-static-library \
        --optimize-for-size \
        --amalgamation \
        --minimized-build \
        --without-documentation \
    && make -j"$(nproc)" install DESTDIR=/tmp/root
RUN ldconfig /


# build binary
FROM arm64v8/alpine:edge AS build

# Environment
ENV KEA_VERSION="1.6.0-beta"
ARG BUILD_PKGS="build-base clang boost-dev postgresql-dev mariadb-dev gawk bison flex lld perl autoconf automake libtool "
ARG CFLAGS="-O2 -pthread -pipe -fPIC -FORTIFY_SOURCE=2 -fPIE "
ARG CXXFLAGS="${CFLAGS} "
ARG CPPFLAGS="-O2 -DOS_LINUX -DBOOST_ASIO_HEADER_ONLY "
ARG LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -fuse-ld=lld "
ENV CC="clang "
ENV CXX="clang++ "

# dev package install
COPY --from=log4cplus /tmp/root /
COPY --from=botan /tmp/root /
#RUN echo "@comm http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update ${BUILD_PKGS}
## build
RUN mkdir -p /tmp/build \
  && wget "https://ftp.isc.org/isc/kea/${KEA_VERSION}/kea-${KEA_VERSION}.tar.gz" -O kea.tar.gz \
  && tar xf kea.tar.gz --strip-components=1 -C /tmp/build \
  && rm kea.tar.gz
RUN cd /tmp/build \
  && autoreconf -if \
  && autoreconf --install \
  && ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-rpath \
    --disable-static \
    --with-boost-include \
    --with-botan-config \
    --with-mysql \
    --with-pgsql \
    --with-log4cplus \
    --disable-dependency-tracking \
    CFLAGS="${CFLAGS}" CXXFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
RUN cd /tmp/build \
    && make -j "$(nproc)"
RUN cd /tmp/build \
    && make install DESTDIR=/tmp/root
RUN ldconfig /
# Delete unnecessary directory
RUN rm -rf /tmp/root/var/run /tmp/root/usr/local/share/man/* /tmp/root/usr/local/include /tmp/root/usr/include \
           /tmp/root/usr/share/kea /tmp/root/usr/share/doc/kea


# Intermediate container with runtime dependencies
FROM arm64v8/alpine:edge AS runtime

# Install runtime dependencies
ARG RUN_PKGS="libgcc libstdc++ boost-system mariadb-connector-c libpq tzdata "
#RUN echo "@comm http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
COPY --from=log4cplus /tmp/root /
COPY --from=botan /tmp/root /
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update --no-cache ${RUN_PKGS} \
    && rm -rf /var/cache/apk/* /usr/local/share/man/* \
    && mkdir -p /var/lib/kea


# Final container
FROM runtime
LABEL maintainer="kometchtech <kometch@gmail.com>" \
      arch="Aarch64" \
      description="Kea is an open source implementation of the Dynamic Host Configuration \
                   Protocol (DHCP) servers, developed and maintained by Internet Systems Consortium (ISC)." \
      url="https://www.isc.org/kea/"

# Environment
ENV TZ Asia/Tokyo

# publish port
EXPOSE 67/udp 547/udp

# service running
STOPSIGNAL SIGTERM

# select entrypoint
WORKDIR /etc/kea
#CMD ["/usr/local/sbin/keactrl", "start"]
COPY ./run.sh /usr/local/bin/
ENTRYPOINT ["run.sh"]

# Fetch isc Kea libraries from build image
COPY --from=build /tmp/root/ /
RUN ldconfig /
