version: 2
registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: kometchtech
    password: "${{secrets.DOCKER_REGISTRY_REGISTRY_HUB_DOCKER_COM_PASSWORD}}"

updates:
- package-ecosystem: docker
  directory: "/bind"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/dnscrypt-proxy"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/knot"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/kresd"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/nsd"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/dnsdist"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/pdnsrec"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/stubby"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/unbound"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/zabbix-agent"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  open-pull-requests-limit: 10
  registries:
  - docker-registry-registry-hub-docker-com
