name: Build and Push Multi-Arch Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/VERSION'
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - linux/amd64 
          - linux/arm64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全コミットを取得

      - name: Determine previous commit
        id: previous-commit
        run: |
          if [ -z "${{ github.event.before }}" ] || ! git rev-parse ${{ github.event.before }} >/dev/null 2>&1; then
            BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          else
            BEFORE_COMMIT=${{ github.event.before }}
          fi
          echo "before_commit=$BEFORE_COMMIT" >> $GITHUB_ENV

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "$before_commit" ]; then
            CHANGED_DIRS=$(git diff --name-only $before_commit HEAD | grep -E 'Dockerfile|VERSION' | xargs -I {} dirname {} | sort -u | uniq)
            echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_ENV
          else
            echo "No previous commit found, skipping build."
            echo "changed_dirs=" >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set VERSION environment variable
        id: set-version
        run: |
          for dir in ${{ env.changed_dirs }}; do
            if [ -f "$dir/VERSION" ]; then
              RELEASE_VERSION=$(cat $dir/VERSION | tr -d ' ')  # VERSIONファイルからバージョンを取得
              echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV  # 環境変数にセット
              echo "Version set to: $RELEASE_VERSION"
            else
              echo "No VERSION file found in $dir, skipping..."
            fi
          done

      - name: Build and push images for ${{ matrix.platform }}
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.changed_dirs }}
          push: true
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            VERSION=${{ env.RELEASE_VERSION }}
          no-cache: ${{ inputs.no-cache == true }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: |
            type=image,name=${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }},push-by-digest=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build-and-push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

    outputs:
      version: ${{ env.VERSION }}
      platforms: ${{ toJson(matrix.platform) }}  # <-- ARCHS を outputs に追加
      changed_dirs: ${{ env.changed_dirs }}

  manifest:
    needs: 
      - build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load version and platforms from previous step
        run: |
          echo "VERSION=${{ needs.build-and-push.outputs.version }}" >> $GITHUB_ENV
          echo "ARCHS=${{ needs.build-and-push.outputs.platforms }}" >> $GITHUB_ENV

      - name: Debug ARCHS
        run: echo "ARCHS=${{ needs.build-and-push.outputs.platforms }}"

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "${{ needs.build-and-push.outputs.changed_dirs }}" ]; then
            echo "changed_dirs=${{ needs.build-and-push.outputs.changed_dirs }}" >> $GITHUB_ENV
          else
            echo "No previous commit found, skipping build."
            echo "changed_dirs=" >> $GITHUB_ENV
          fi

      - name: Set VERSION environment variable
        id: set-version
        run: |
          for dir in ${{ env.changed_dirs }}; do
            if [ -f "$dir/VERSION" ]; then
              RELEASE_VERSION=$(cat "$dir/VERSION" | tr -d ' \t\n\r')
              echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
              echo "Version found: $RELEASE_VERSION in $dir"
              break
            fi
          done

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          for dir in ${{ env.changed_dirs }}; do
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${dir#./}"
            
            # プラットフォーム固有のダイジェストを収集
            digests=()
            for digest in *; do
              digests+=("$IMAGE_NAME@sha256:$digest")
            done
            # バージョンタグでマニフェストを作成・プッシュ
            docker buildx imagetools create -t $IMAGE_NAME:${{ env.RELEASE_VERSION }} ${digests[@]}
            # mainブランチの場合、latestタグも作成
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              docker buildx imagetools create -t $IMAGE_NAME:latest ${digests[@]}
            fi
          done
