name: Build and Push Multi-Arch Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/VERSION'
      - '**/entrypoint.sh'
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find-dirs.outputs.directories }}
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全コミットを取得

      - name: Determine previous commit
        id: previous-commit
        run: |
          if [ -z "${{ github.event.before }}" ] || ! git rev-parse ${{ github.event.before }} >/dev/null 2>&1; then
            BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          else
            BEFORE_COMMIT=${{ github.event.before }}
          fi
          echo "before_commit=$BEFORE_COMMIT" >> $GITHUB_ENV

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "${{ env.before_commit }}" ]; then
            CHANGED_DIRS=$(git diff --name-only ${{ env.before_commit }} HEAD | grep -E 'Dockerfile|VERSION|entrypoint.sh' | xargs -I {} dirname {} | sort -u | uniq)
            if [ -n "$CHANGED_DIRS" ]; then
              # 配列を作成
              DIRS_JSON="["
              for dir in $CHANGED_DIRS; do
                if [ "$DIRS_JSON" != "[" ]; then
                  DIRS_JSON="$DIRS_JSON,"
                fi
                DIRS_JSON="$DIRS_JSON\"$dir\""
              done
              DIRS_JSON="$DIRS_JSON]"
              echo "directories=$DIRS_JSON" >> $GITHUB_OUTPUT
              echo "Changed directories: $CHANGED_DIRS"
            else
              echo "No relevant changes found"
              echo "directories=[]" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous commit found, skipping build."
            echo "directories=[]" >> $GITHUB_OUTPUT
          fi

  build:
    needs: prepare
    if: needs.prepare.outputs.directories != '[]'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          IMAGE_NAME=$(basename ${{ matrix.directory }})
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Set VERSION environment variable
        id: set-version
        run: |
          if [ -f "source/${{ matrix.directory }}/VERSION" ]; then
            RELEASE_VERSION=$(cat "source/${{ matrix.directory }}/VERSION" | tr -d ' \n\t\r')
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
            echo "Version set to: ${RELEASE_VERSION}"
          else
            echo "No VERSION file found, using latest"
            echo "release_version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: source/${{ matrix.directory }}
          platforms: ${{ matrix.platform }}
          push: true
          no-cache: ${{ inputs.no-cache == true }}
          build-args: |
            VERSION=${{ steps.set-version.outputs.release_version }}
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=max,scope=${{ env.IMAGE_NAME }}-${{ env.PLATFORM_PAIR }}
          outputs: type=image,name=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.IMAGE_NAME }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          retention-days: 1
          if-no-files-found: error

  merge:
    needs: [prepare, build]
    if: needs.prepare.outputs.directories != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Set environment variables
        run: |
          IMAGE_NAME=$(basename ${{ matrix.directory }})
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ env.IMAGE_NAME }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set VERSION environment variable
        id: set-version
        run: |
          if [ -f "source/${{ matrix.directory }}/VERSION" ]; then
            RELEASE_VERSION=$(cat "source/${{ matrix.directory }}/VERSION" | tr -d ' \n\t\r')
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
            echo "Version set to: ${RELEASE_VERSION}"
          else
            echo "No VERSION file found, using latest"
            echo "release_version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          # ダイジェストファイルが存在するか確認
          if [ -z "$(find . -type f -not -path '*/\.*')" ]; then
            echo "No digest files found"
            exit 1
          fi
          
          # ダイジェストファイルのリストを表示
          echo "Found digest files:"
          find . -type f -not -path '*/\.*' | sort
          
          # マニフェストリストを作成
          docker buildx imagetools create \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-version.outputs.release_version }} \
            $(printf '${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
          
          # latestタグも作成
          docker buildx imagetools create \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            $(printf '${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
          
          echo "Created and pushed manifest list for ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}"
