name: Build and Push Multi-Arch Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/VERSION'
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全コミットを取得

      - name: Ensure latest commit is checked out
        run: git checkout ${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine previous commit
        id: previous-commit
        run: |
          if [ -z "${{ github.event.before }}" ] || ! git rev-parse ${{ github.event.before }} >/dev/null 2>&1; then
            BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          else
            BEFORE_COMMIT=${{ github.event.before }}
          fi
          echo "before_commit=$BEFORE_COMMIT" >> $GITHUB_ENV

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "$before_commit" ]; then
            CHANGED_DIRS=$(git diff --name-only $before_commit HEAD | grep -E 'Dockerfile|VERSION' | xargs -I {} dirname {} | sort -u | uniq)
            echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_ENV
          else
            echo "No previous commit found, skipping build."
            echo "changed_dirs=" >> $GITHUB_ENV
          fi

      - name: Set VERSION environment variable
        id: set-version
        run: |
          for dir in ${{ env.changed_dirs }}; do
            if [ -f "$dir/VERSION" ]; then
              RELEASE_VERSION=$(cat $dir/VERSION | tr -d ' ')  # VERSIONファイルからバージョンを取得
              echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV  # 環境変数にセット
              echo "Version set to: $RELEASE_VERSION"
            else
              echo "No VERSION file found in $dir, skipping..."
            fi
          done

      - name: Build and push images for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}:${{ env.RELEASE_VERSION }}
          platforms: ${{ matrix.platform }}
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
          context: ${{ env.changed_dirs }}
          push: true
          no-cache: ${{ inputs.no-cache == true }}
          outputs: type=image,"name=docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}",push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    needs: 
      - build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read version from VERSION file
        id: set-version
        run: echo "VERSION=$(cat ./VERSION | tr -d ' ')" >> $GITHUB_ENV

      - name: Create Docker Manifest List
        working-directory: ${{ runner.temp }}/digests
        run: |
          ARCHS="${{ matrix.platform }}"  # 必要なアーキテクチャを列挙（将来追加可）
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}"
          
          # `--amend` を動的に構築
          AMEND_ARGS=""
          for ARCH in $ARCHS; do
            AMEND_ARGS="$AMEND_ARGS --amend $IMAGE_NAME:${VERSION}"
          done

          # マルチアーキテクチャの Docker イメージを作成・プッシュ
          docker manifest create $IMAGE_NAME:${VERSION} $AMEND_ARGS
          docker manifest push $IMAGE_NAME:${VERSION}

      - name: Create and Push Docker Manifest (Latest)
        working-directory: ${{ runner.temp }}/digests
        if: github.ref == 'refs/heads/main'
        run: |
          ARCHS="${{ matrix.platform }}"
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.changed_dirs }}"

          AMEND_ARGS=""
          for ARCH in $ARCHS; do
            AMEND_ARGS="$AMEND_ARGS --amend $IMAGE_NAME:${VERSION}"
          done

          docker manifest create $IMAGE_NAME:latest $AMEND_ARGS
          docker manifest push $IMAGE_NAME:latest

