name: Build and Push Multi-Arch Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/VERSION'
      - '**/entrypoint.sh'
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find-dirs.outputs.directories }}
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全コミットを取得

      - name: Determine previous commit
        id: previous-commit
        run: |
          if [ -z "${{ github.event.before }}" ] || ! git rev-parse ${{ github.event.before }} >/dev/null 2>&1; then
            BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          else
            BEFORE_COMMIT=${{ github.event.before }}
          fi
          echo "before_commit=$BEFORE_COMMIT" >> $GITHUB_ENV

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "${{ env.before_commit }}" ]; then
            CHANGED_DIRS=$(git diff --name-only ${{ env.before_commit }} HEAD | grep -E 'Dockerfile|VERSION|entrypoint.sh' | xargs -I {} dirname {} | sort -u | uniq)
            if [ -n "$CHANGED_DIRS" ]; then
              # 配列を作成
              DIRS_JSON="["
              for dir in $CHANGED_DIRS; do
                if [ "$DIRS_JSON" != "[" ]; then
                  DIRS_JSON="$DIRS_JSON,"
                fi
                DIRS_JSON="$DIRS_JSON\"$dir\""
              done
              DIRS_JSON="$DIRS_JSON]"
              echo "directories=$DIRS_JSON" >> $GITHUB_OUTPUT
              echo "Changed directories: $CHANGED_DIRS"
            else
              echo "No relevant changes found"
              echo "directories=[]" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous commit found, skipping build."
            echo "directories=[]" >> $GITHUB_OUTPUT
          fi

  build:
    needs: prepare
    if: needs.prepare.outputs.directories != '[]'
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Get image name from directory
        id: image-name
        run: |
          IMAGE_NAME=$(basename ${{ matrix.directory }})
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Set VERSION environment variable
        id: set-version
        run: |
          if [ -f "source/${{ matrix.directory }}/VERSION" ]; then
            RELEASE_VERSION=$(cat "source/${{ matrix.directory }}/VERSION" | tr -d ' \n\t\r')
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
            echo "Version set to: ${RELEASE_VERSION}"
          else
            echo "No VERSION file found, using latest"
            echo "release_version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Get architecture suffix
        id: arch-suffix
        run: |
          if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            echo "suffix=amd64" >> $GITHUB_OUTPUT
          else
            echo "suffix=arm64" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Container Registryにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker Hubにログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # GitHub Container Registryにビルドとプッシュ（ダイジェスト形式）
      - name: Build and push to GitHub Container Registry
        id: build-ghcr
        uses: docker/build-push-action@v6
        with:
          context: source/${{ matrix.directory }}
          platforms: ${{ matrix.platform }}
          push: true
          no-cache: ${{ inputs.no-cache == true }}
          build-args: |
            VERSION=${{ steps.set-version.outputs.release_version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-${{ steps.arch-suffix.outputs.suffix }}
          outputs: type=image,name=ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }},push-by-digest=true

      # Docker Hubにビルドとプッシュ（同じダイジェストを再利用）
      - name: Copy image to Docker Hub
        env:
          GHCR_DIGEST: ${{ steps.build-ghcr.outputs.digest }}
        run: |
          # Pull the image by digest from GitHub Container Registry
          docker pull ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${GHCR_DIGEST}

          # Tag for Docker Hub with architecture tag
          docker tag ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${GHCR_DIGEST} \
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-${{ steps.arch-suffix.outputs.suffix }}

          # Push to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-${{ steps.arch-suffix.outputs.suffix }}

      # GitHub Container Registry用のダイジェストをエクスポート
      - name: Export digest
        env:
          DIGEST: ${{ steps.build-ghcr.outputs.digest }}
        run: |
          mkdir -p /tmp/digests
          echo "${{ matrix.platform }}=${DIGEST}" >> /tmp/digests/ghcr-${{ steps.arch-suffix.outputs.suffix }}
          echo "${{ matrix.platform }},${{ steps.arch-suffix.outputs.suffix }}" >> /tmp/digests/mapping-${{ steps.arch-suffix.outputs.suffix }}

      # ダイジェストをアップロード
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ steps.image-name.outputs.image_name }}-${{ steps.arch-suffix.outputs.suffix }}
          path: /tmp/digests/
          retention-days: 1

  # GitHub Container Registry のマニフェスト作成
  create-ghcr-manifest:
    needs: [prepare, build]
    if: needs.prepare.outputs.directories != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Get image name from directory
        id: image-name
        run: |
          IMAGE_NAME=$(basename ${{ matrix.directory }})
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Set VERSION environment variable
        id: set-version
        run: |
          if [ -f "source/${{ matrix.directory }}/VERSION" ]; then
            RELEASE_VERSION=$(cat "source/${{ matrix.directory }}/VERSION" | tr -d ' \n\t\r')
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
            echo "Version set to: ${RELEASE_VERSION}"
          else
            echo "No VERSION file found, using latest"
            echo "release_version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ steps.image-name.outputs.image_name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest for GitHub Container Registry
        run: |
          # ファイル一覧を表示（デバッグ用）
          find /tmp/digests -type f -ls
          
          # アーキテクチャとダイジェストのマッピングを取得
          if [ -f "/tmp/digests/ghcr-amd64" ] && [ -f "/tmp/digests/ghcr-arm64" ] && [ -f "/tmp/digests/mapping-amd64" ] && [ -f "/tmp/digests/mapping-arm64" ]; then
            AMD64_DIGEST=$(cat /tmp/digests/ghcr-amd64 | cut -d '=' -f2)
            ARM64_DIGEST=$(cat /tmp/digests/ghcr-arm64 | cut -d '=' -f2)
            
            echo "AMD64 digest: ${AMD64_DIGEST}"
            echo "ARM64 digest: ${ARM64_DIGEST}"
            
            # バージョンタグのマニフェスト作成
            echo "Creating manifest with version tag: ${{ steps.set-version.outputs.release_version }}"
            docker manifest create \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }} \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${AMD64_DIGEST} \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${ARM64_DIGEST}
            
            # マニフェストをプッシュ
            docker manifest push ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}
            
            # latestタグのマニフェスト作成
            echo "Creating manifest with latest tag"
            docker manifest create \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}:latest \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${AMD64_DIGEST} \
              ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}@${ARM64_DIGEST}
            
            # latestマニフェストをプッシュ
            docker manifest push ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}:latest
            
            echo "Created and pushed manifest list for ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image_name }}"
          else
            echo "Error: Required digest files are missing"
            exit 1
          fi

  # Docker Hub のマニフェスト作成
  create-dockerhub-manifest:
    needs: [prepare, build]
    if: needs.prepare.outputs.directories != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.prepare.outputs.directories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Get image name from directory
        id: image-name
        run: |
          IMAGE_NAME=$(basename ${{ matrix.directory }})
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Set VERSION environment variable
        id: set-version
        run: |
          if [ -f "source/${{ matrix.directory }}/VERSION" ]; then
            RELEASE_VERSION=$(cat "source/${{ matrix.directory }}/VERSION" | tr -d ' \n\t\r')
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
            echo "Version set to: ${RELEASE_VERSION}"
          else
            echo "No VERSION file found, using latest"
            echo "release_version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ steps.image-name.outputs.image_name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest for Docker Hub
        run: |
          # ファイル一覧を表示（デバッグ用）
          find /tmp/digests -type f -ls
          
          # アーキテクチャマッピングファイルが存在することを確認
          if [ -f "/tmp/digests/mapping-amd64" ] && [ -f "/tmp/digests/mapping-arm64" ]; then
            # バージョンタグのマニフェスト作成
            echo "Creating manifest with version tag: ${{ steps.set-version.outputs.release_version }}"
            docker manifest create \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }} \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-amd64 \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-arm64
            
            # マニフェストをプッシュ
            docker manifest push ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}
            
            # latestタグのマニフェスト作成
            echo "Creating manifest with latest tag"
            docker manifest create \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:latest \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-amd64 \
              ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:${{ steps.set-version.outputs.release_version }}-arm64
            
            # latestマニフェストをプッシュ
            docker manifest push ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}:latest
            
            echo "Created and pushed manifest list for ${{ secrets.DOCKER_USERNAME }}/${{ steps.image-name.outputs.image_name }}"
          else
            echo "Error: Mapping files are missing"
            exit 1
          fi