name: Docker Multi-Architecture Build

on:
  workflow_dispatch:
    inputs:
      app_directory:
        description: 'Directory of the application to build'
        required: true
        type: string
      no-cache:
        description: 'Disable build cache'
        required: false
        type: boolean
        default: false
  push:
    paths:
      - '**/Dockerfile'
      - '**/VERSION'
      - '**/entrypoint.sh'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find-dirs.outputs.directories }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全コミットを取得

      - name: Determine previous commit
        id: previous-commit
        run: |
          if [ -z "${{ github.event.before }}" ] || ! git rev-parse ${{ github.event.before }} >/dev/null 2>&1; then
            BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          else
            BEFORE_COMMIT=${{ github.event.before }}
          fi
          echo "before_commit=$BEFORE_COMMIT" >> $GITHUB_ENV

      - name: Find modified directories
        id: find-dirs
        run: |
          if [ -n "${{ env.before_commit }}" ]; then
            CHANGED_DIRS=$(git diff --name-only ${{ env.before_commit }} HEAD | grep -E 'Dockerfile|VERSION|entrypoint.sh' | xargs -I {} dirname {} | sort -u | uniq)
            if [ -n "$CHANGED_DIRS" ]; then
              # 配列を作成
              DIRS_JSON="["
              for dir in $CHANGED_DIRS; do
                if [ "$DIRS_JSON" != "[" ]; then
                  DIRS_JSON="$DIRS_JSON,"
                fi
                DIRS_JSON="$DIRS_JSON\"$dir\""
              done
              DIRS_JSON="$DIRS_JSON]"
              echo "directories=$DIRS_JSON" >> $GITHUB_OUTPUT
              echo "Changed directories: $CHANGED_DIRS"
            else
              echo "No relevant changes found"
              echo "directories=[]" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous commit found, skipping build."
            echo "directories=[]" >> $GITHUB_OUTPUT
          fi
          
      - name: Set workflow dispatch directory
        if: github.event_name == 'workflow_dispatch'
        run: |
          DIRS_JSON="[\"${{ github.event.inputs.app_directory }}\"]"
          echo "directories=$DIRS_JSON" >> $GITHUB_OUTPUT

      - name: Get version from VERSION file
        id: get-version
        if: github.event_name == 'workflow_dispatch'
        run: |
          APP_DIR="${{ github.event.inputs.app_directory }}"
          if [ -f "${APP_DIR}/VERSION" ]; then
            VERSION=$(cat "${APP_DIR}/VERSION" | tr -d '\n')
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "Error: VERSION file not found in ${APP_DIR}"
            exit 1
          fi

  build:
    needs: prepare
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set architecture suffix
        id: arch-suffix
        run: |
          echo "suffix=${{ matrix.arch }}" >> $GITHUB_OUTPUT

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./${{ needs.prepare.outputs.app_directory }}
          file: ./${{ needs.prepare.outputs.app_directory }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          no-cache: ${{ inputs.no-cache == true }}
          build-args: |
            VERSION=${{ needs.prepare.outputs.version }}
          cache-from: type=gha,scope=platform-${{ steps.arch-suffix.outputs.suffix }}
          cache-to: type=gha,mode=max,scope=platform-${{ steps.arch-suffix.outputs.suffix }}
          outputs: type=image,name=kometchtech/${{ needs.prepare.outputs.image_name }},push-by-digest=true,name-canonical=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          echo "${{ matrix.platform }},${{ steps.build.outputs.digest }}" >> /tmp/digests/digest-${{ steps.arch-suffix.outputs.suffix }}
          cat /tmp/digests/digest-${{ steps.arch-suffix.outputs.suffix }}

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ needs.prepare.outputs.image_name }}-${{ steps.arch-suffix.outputs.suffix }}
          path: /tmp/digests/digest-${{ steps.arch-suffix.outputs.suffix }}
          retention-days: 1

  merge:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ needs.prepare.outputs.image_name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        run: |
          APP_NAME="${{ needs.prepare.outputs.image_name }}"
          VERSION="${{ needs.prepare.outputs.version }}"
          
          # Parse the digests collected from the previous step
          DIGESTS=""
          for FILE in /tmp/digests/digest-*; do
            while IFS= read -r line; do
              PLATFORM=$(echo $line | cut -d ',' -f 1)
              DIGEST=$(echo $line | cut -d ',' -f 2)
              DIGESTS="${DIGESTS} ${DIGEST}"
            done < $FILE
          done
          
          # Create versioned tag
          docker buildx imagetools create -t kometchtech/${APP_NAME}:${VERSION} ${DIGESTS}
          
          # Create latest tag
          docker buildx imagetools create -t kometchtech/${APP_NAME}:latest ${DIGESTS}
